.TH "gbs3" "1" "March 2021" "Ubuntu" "User Commands"

.SH "NAME"
gbs3 \- GAMBAS Scripter

.SH "SYNOPSIS"
.B gbs3
[options] [--] [<script file> | -]
.br
.B gbs3
--convert-project <source project directory> <destination script directory>

.SH "DESCRIPTION"
Gambas is a free development environment based on a Basic interpreter with object extensions,
.br
a mix of Java(tm) and Visual Basic(tm).
.br
With Gambas, you can quickly design your program GUI, access MySQL or PostgreSQL databases,
.br
pilot KDE applications with DCOP, translate your program into many languages, and so on...

.B gbs3 
is the interpreter that allows you to compile and execute a Gambas script.
.br
.B gbs3
may also be used to convert a gambas project to a script

.SH "OPTIONS"
.TP
\fB\-b, --buildonly\fR
process and compile the script without executing it
.TP
\fB\-c, --nocache\fR
force the script compilation (do not check cache)
.TP
\fB\-e\fR
execute the source code provided by the command line ( ':' separator )
.TP
\fB\-f, --fast\fR
use just-in-time compiler
TP
\fB\-g, --debug\fR
add debugging information to application
.TP
\fB\-h, --help\fR
display help and exit
.TP
\fB\-l, --list\fR
display a list of available Components or Libraries, '-l component' or '-l library'
.TP
\fB\-L, --license\fR
display license
.TP
\fB\-S --strict\fR
fail if 'Public' or 'Sub' are defined without a 'main' function otherwise create main()
.TP
\fB\-t, --trace\fR
turn on tracing option during execution
.TP
\fB\-T, --terse\fR
only print a very terse error report on compile errors
.TP
\fB\-u, --use\fR
load component or libraries ('comp1,comp2,lib1...')
.TP
\fB\-v, --verbose\fR
be verbose
.TP
\fB\-V, --version\fR
display version
.TP
\fB\-w, --warnings\fR
display warnings during compilation
.TP
\fB\--convert-project\fR
convert a simple project to a script

.SH "PROJECT CONVERSION"
.B gbs3
can convert a gambas project to an executable script file using the --convert-project option.
.br
The input project directory is used to createthe script which is written to the output script directory.
.br
The script is created and named the same as the originating project.

.B gbs3
MyProjectDirectory DestinationScriptDirectory

.SH "EXAMPLE"

#!/usr/bin/env gbs3
.br
for i as integer = 0 to 10
.br
  print i;;
.br
next

.SH "AVAILABILITY"
The latest version of Gambas can always be obtained from
\fBgambas.sourceforge.net\fR, documentation about the language is at
\fBhttp://gambaswiki.org/wiki\fR.

.SH "REPORTING BUGS"
Report bugs to \fBhttp://gambaswiki.org/bugtracker\fR

.SH "COPYRIGHT"
Copyright\(co Benoît Minisini <g4mba5@gmail.com>;
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
