' Gambas module file

Public Sub Main()

  Dim hSettings As Settings

  hSettings = New Settings("~/gambas/git/stable/app/src/gambas3/.settings")
  Print hSettings["/Debug/Projects"]

End

' Private Sub Dump(hSettings As Settings)
' 
'   Dim sSlot As String
'   Dim sKey As String
' 
'   For Each sSlot In hSettings.Keys
'     
'     Print "["; sSlot; "]"
'     For Each sKey In hSettings.Keys[sSlot]
'       Print sKey; "="; hSettings[sSlot &/ sKey]
'     Next
'     
'   Next
'   Print
' 
' End
' 
