' Gambas module file

Fast


Public Function awef(Kuka As ChildClass, Kenet As BaseClass) As Boolean 
  
  Return True
  
End


Public Sub JITTest100(iX As Integer, iY As Integer, iZ As Integer, Optional PlotMode As Boolean = False, Optional bDebug As Boolean = False)
Dim Saatm As New Integer[4]
Dim SoluX As Integer, SoluY As Integer 
Dim ii As Integer, jj As Integer, nn As Integer
Dim tmpX As Integer, tmpY As Integer

Dim iRain As Integer
Dim pWinds As New POINT[]
Dim pWind As New POINTFloat(0, 0)
Dim tmpPoint As POINT
Dim tmpPointf As New POINTFloat
Dim fWind As Float
Dim iEta As Integer
Dim iPower As Integer[] = [100, 75, 25, 10, 2, 1]
Dim hh As New TestClass2
   
Dim fTimeOfDay As Float = Abs(1 - Abs(((mTest.timo - (mTest.gDay * 3)) / mTest.gHour) - 0.5) * 2)
 'peak 23:00 - 06:00... --> 03:00  = 0
 '                          15:00  = 1

Dim fTmp As Float

      If PlotMode = True Then
       ' iX = CInt((Peli.KokoKartX / MATSIZE) * iX) 
       ' iY = CInt((Peli.KokoKartY / MATSIZE) * iY) 
      Endif

  

End